services:
  db:
    image: postgres:latest
    container_name: contender_projetao_dev
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "_DbContext@1@3#24*"
      POSTGRES_DB: db-instituicao
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .

    restart: always
    container_name:  SpringApp

    depends_on: 
      - db

       
volumes:
  pgdata: 